name: diabetes-env
channels:
  - defaults
dependencies:
  - python=3.12
  - pandas
  - scikit-learn
  - pip
  - pip:
      - mlflow
      - imbalanced-learn
      - joblib
      - google-api-python-client
      - google-auth
      - google-auth-httplib2
      - google-auth-oauthlib
