name: mlflow-diabetes-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - pandas
      - scikit-learn
      - imbalanced-learn
      - mlflow
      - joblib
