name: MLflow CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  mlflow-train-upload-docker:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: MLProject

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn mlflow imbalanced-learn joblib \
                    google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib

    - name: Run MLflow training script
      run: python modelling.py

    - name: Get latest MLflow run ID
      id: get_run_id
      run: |
        RUN_ID=$(ls -td mlruns/0/* | head -1 | xargs -n 1 basename)
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "Latest RUN_ID: $RUN_ID"

    - name: Copy rf_model.pkl to MLProject folder as model.pkl
      run: cp mlruns/0/$RUN_ID/artifacts/rf_model.pkl model.pkl

    - name: Save GDrive credentials file
      run: echo "${{ secrets.GDRIVE_CREDENTIALS }}" > gdrive_credentials.json

    - name: Upload model to Google Drive
      run: python upload_to_gdrive.py
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ./gdrive_credentials.json

    - name: Build Docker image from MLflow model
      run: |
        mlflow models build-docker -m "mlruns/0/$RUN_ID/artifacts/model" -n diabetes-model

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag Docker image
      run: docker tag diabetes-model ${{ secrets.DOCKER_USERNAME }}/diabetes-model:latest

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/diabetes-model:latest
