name: CI MLflow Train

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Setup Conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: MLProject/conda.yaml
        activate-environment: mlflow-env
        auto-activate-base: false
        auto-update-conda: true

    - name: Install MLflow and others
      shell: bash -l {0}
      run: |
        pip install mlflow imbalanced-learn joblib scikit-learn pandas

    - name: Run MLflow project
      shell: bash -l {0}
      working-directory: MLProject
      run: mlflow run . --no-conda
