name: MLflow CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  mlflow-train-upload-docker:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: MLProject

    env:
      FOLDER_ID: 1ctX93YMRqRLHd_OhJ32iA22wvDzBWEQY

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow pandas scikit-learn imbalanced-learn joblib \
                    google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib

    - name: Run MLflow project (modelling.py via MLproject)
      run: |
        mlflow run . -P n_estimators=100 --env-manager=local

    - name: Get latest MLflow run ID
      id: get_run_id
      run: |
        RUN_ID=$(ls -td mlruns/0/* | head -1 | xargs -n 1 basename)
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "Latest RUN_ID: $RUN_ID"

    # --- SANGAT PENTING: TAMBAHAN DEBUGGING UNTUK VERIFIKASI STRUKTUR ARTIFACTS ---
    - name: Verify MLflow run structure and artifacts
      run: |
        echo "--- Listing contents of mlruns/0/${{ env.RUN_ID }} ---"
        ls -R mlruns/0/${{ env.RUN_ID }}
        echo "--- End of mlruns/0/${{ env.RUN_ID }} contents ---"

        echo "--- Listing contents of mlruns/0/${{ env.RUN_ID }}/artifacts ---"
        ls -R mlruns/0/${{ env.RUN_ID }}/artifacts || echo "artifacts directory not found!"
        echo "--- End of artifacts contents ---"

        echo "--- Listing contents of mlruns/0/${{ env.RUN_ID }}/artifacts/model ---"
        ls -R mlruns/0/${{ env.RUN_ID }}/artifacts/model || echo "model directory inside artifacts not found!"
        echo "--- End of model contents ---"
    # --- AKHIR DEBUGGING TAMBAHAN ---


    - name: Copy model file to root for GDrive upload
      run: |
        # Path ini seharusnya sudah benar jika upload ke GDrive berhasil
        # Berdasarkan output terakhir, ini berhasil.
        cp mlruns/0/${{ env.RUN_ID }}/artifacts/rf_model.pkl model.pkl # Ganti ke rf_model.pkl jika itu yang berhasil diunggah

    - name: Decode GDrive credentials
      run: echo "${{ secrets.GDRIVE_CREDENTIALS }}" | base64 --decode > gdrive_credentials.json

    - name: Upload model.pkl to Google Drive
      run: python upload_to_gdrive.py model.pkl $FOLDER_ID
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ./gdrive_credentials.json

    - name: Build Docker image from MLflow model
      run: |
        # Path yang ini *harus* menunjuk ke direktori 'model' yang dibuat oleh mlflow.sklearn.log_model
        # Kita perlu memastikan direktori ini ada dan berisi MLmodel, conda.yaml, dll.
        mlflow models build-docker \
          -m "mlruns/0/${{ env.RUN_ID }}/artifacts/model" \
          -n diabetes-model

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag Docker image
      run: docker tag diabetes-model ${{ secrets.DOCKER_USERNAME }}/diabetes-model:latest

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/diabetes-model:latest
