name: MLflow Training

on:
  push:
    paths:
      - 'MLProject/**'
      - '.github/workflows/mlflow_ci.yaml'

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Conda Environment
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: MLProject/conda.yaml
        environment-name: mlflow-env
        init-shell: bash
        cache-environment: true

    - name: Run MLflow model training
      shell: bash -l {0}
      run: |
        cd MLProject
        mlflow run . --env-manager=local
      env:
        MLFLOW_EXPERIMENT_NAME: "Diabetes Prediction"
