name: CI MLflow Train

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: MLProject/conda.yaml
          activate-environment: mlflow-env
          auto-activate-base: false

      - name: Install Python dependencies
        run: |
          pip install mlflow scikit-learn imbalanced-learn pandas joblib google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . --env-manager=local

      - name: Save GDrive credentials
        run: echo "${{ secrets.GDRIVE_CREDENTIALS }}" > MLProject/credentials.json

      - name: Upload model to Google Drive
        run: |
          cd MLProject
          python upload_to_gdrive.py model/model.pkl

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          mlflow models build-docker -m MLProject/model -n ${{ secrets.DOCKER_USERNAME }}/mlflow-model:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mlflow-model:latest
