name: CI MLflow Train & Docker Build

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: MLProject/conda.yaml
          activate-environment: mlflow-env
          auto-activate-base: false

      - name: Install MLflow and dependencies
        run: |
          pip install mlflow scikit-learn imbalanced-learn pandas joblib gdown

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . --env-manager=local

      - name: Get latest MLflow run ID
        id: get_run_id
        run: |
          RUN_ID=$(mlflow runs list --order-by start_time desc | awk 'NR==2 {print $1}')
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      - name: Upload model to Google Drive
        run: |
          echo "${{ secrets.GDRIVE_CREDENTIALS }}" > credentials.json
          export GOOGLE_APPLICATION_CREDENTIALS=credentials.json
          pip install --upgrade gdown
          cd MLProject
          MODEL_PATH=$(mlflow artifacts download -r ${{ env.RUN_ID }} -a model)
          gdown upload $MODEL_PATH --folder https://drive.google.com/drive/folders/YOUR_FOLDER_ID
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}

      - name: Build Docker Image from MLflow Model
        run: |
          cd MLProject
          mlflow models build-docker -m runs:/${{ env.RUN_ID }}/model -n eksperimen_sml_image

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag Docker Image
        run: docker tag eksperimen_sml_image ${{ secrets.DOCKER_USERNAME }}/eksperimen_sml_image:latest

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/eksperimen_sml_image:latest
