name: MLflow CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  mlflow-train-upload-docker:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: MLProject

    env:
      FOLDER_ID: 1ctX93YMRqRLHd_OhJ32iA22wvDzBWEQY
      MLFLOW_TRACKING_URI: ./mlruns

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow pandas scikit-learn imbalanced-learn joblib \
                    google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib

    - name: Run MLflow project (modelling.py via MLproject)
      run: |
        mlflow run . -P n_estimators=100 --env-manager=local

    - name: Get latest MLflow run ID
      id: get_run_id
      run: |
        RUN_ID=$(ls -td mlruns/0/* | head -1 | xargs -n 1 basename)
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "Latest RUN_ID: $RUN_ID"

    - name: List model artifacts (debugging)
      run: |
        echo "--- Listing artifacts for run ID: ${{ env.RUN_ID }} ---"
        ls -R mlruns/0/${{ env.RUN_ID }}/artifacts
        echo "--- END OF ARTIFACTS LIST ---"

    - name: Copy model file to root for GDrive upload
      run: |
        cp mlruns/0/${{ env.RUN_ID }}/artifacts/rf_model.pkl model.pkl

    - name: Decode GDrive credentials
      run: echo "${{ secrets.GDRIVE_CREDENTIALS }}" | base64 --decode > gdrive_credentials.json

    - name: Upload model.pkl to Google Drive
      run: python upload_to_gdrive.py model.pkl $FOLDER_ID
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ./gdrive_credentials.json

    - name: Build Docker image from MLflow model
      run: |
        # Perintah build-docker kembali ke bentuk aslinya tanpa opsi yang tidak didukung
        mlflow models build-docker \
          -m "runs:/${{ env.RUN_ID }}/mlflow_sklearn_model" \
          -n diabetes-model

    # Langkah baru untuk debugging: Mencari lokasi Dockerfile yang dihasilkan
    # Perhatikan indentasi untuk setiap baris di bawah 'run: |'
    - name: Debug: List contents of current directory
      run: |
        echo "Listing contents of working directory: MLProject"
        ls -R
        echo "Searching for Dockerfile..."
        find . -name "Dockerfile"

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag Docker image
      run: docker tag diabetes-model ${{ secrets.DOCKER_USERNAME }}/diabetes-model:latest

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/diabetes-model:latest
