name: MLflow Training

on:
  push:
    paths:
      - 'MLProject/**'
      - '.github/workflows/mlflow_ci.yaml'

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        cd MLProject
        pip install -r <(conda env export --from-history | grep -v "^prefix:")

    - name: Run MLflow model training
      run: |
        cd MLProject
        mlflow run . --env-manager=local
      env:
        MLFLOW_EXPERIMENT_NAME: "Diabetes Prediction"
